sudo: required
notifications:
  email: false
services:
- docker

jobs:
  include:
  - stage: Test Gradle build
    before_script:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker build -t verify-saml-extension .
    - "[ -d $(pwd)/artifact ] || mkdir $(pwd)/artifact"
    script:
    - docker run --mount type=bind,source="$(pwd)"/artifact verify-saml-extension test
    after_success:
    - rm -f $(pwd)/artifact/*
    #deploy:
    #- do something here with the gradle test report
  - stage: run clean Gradle build
    before_script:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker build -t verify-saml-extension .
    - "[ -d $(pwd)/artifact ] || mkdir $(pwd)/artifact"
    script:
    - docker run --mount type=bind,source="$(pwd)"/artifact verify-saml-extension build
    deploy:
      provider: s3
      access_key_id: AKIAIRZ4WLJNQX2RWDLA
      secret_access_key:
        secure: Zm7qCYbI5bHGxPvBxgXlNpHkqbOlvVS6VlUWVl5QmuMixQtS5l/UcwP0yXUPwhg1nixYZQRfAMfFHUPz7Z4GLQRr3PZpdxRI2zTY9LsNINvZiQPXWpaLLp4URA94KFjhu4K+gZzuMKWCl6w3JtIqZnz6JmBXtm6UBabKzxY/EmH4lsun0U7/1CrdoaySmSFIS03KfoUWZB8ZpBnXfpI6Jxf3uRfx36C7ftUNY5lBIBtehtxjOeJgOaWAZ2zigZTJbOkEaNd2XZNNL121t/Tde7CzEYqcOUrBF64nCBxf7YWPaRJJC32EoTuN073yF5TiCmPZn3+iHXPUBXJf/HICDmQyi9mXfiUcLt1vf6W8RCjw/sMMw2qA46jUPnlrEpNebeu6aR9zxx00gqs5QcZKLbwmNbJTLHc/+nDdZldiPHESY202CUG8Cs8KLND4aoLf+dng04Lnp2Jh+110L/w4nkL21ZgKGRpJHuLAkqE9+I+wcBOC++HYZpITwauvP3lpmW8DnTi7U+jzboA5DIGItrVyPCLQgX4sjRimJm1xt60XBKzittU5exZ19lnRHG8OLrNWPxCW5PQrOVEBA7zbWNxNirdZRVE89q5rnR2bJ7ompQ8WVy4XhhzQCzTdWz3fW1oGOsRpPLQoWOoXUH/joFPC9lnPqA1S9xy9iySNpE8=
      bucket: verify-release-improvements-artifacts
      region: eu-west-1
      upload-dir: verify-saml-extensions
      file_glob: true
      file: "$(pwd)/artifact/libs/ida-saml-extensions-*.jar"
      acl: bucket_owner_full_control
      on:
        repo: verify-travis-bot/verify-saml-extensions
      skip_cleanup: true
